version: "3.9"
services:
  db:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5438:5432"

  influxdb:
    image: influxdb:latest
    volumes:
      - influxdb2:/.influxdb2
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: admin1234
      DOCKER_INFLUXDB_INIT_ORG: pht
      DOCKER_INFLUXDB_INIT_BUCKET: phtbucket

  mqtt:
    image: fstehle/rpi-mosquitto
    restart: always
    ports:
      - "1883:1883"

  mqtt-bridge:
    image: reap/mqtt-influxdb-bridge
    environment:
      BROKER: tcp://192.168.80.3:1883
      DB: http://192.168.80.4:8086

    depends_on:
      - mqtt
      - influxdb

volumes:
  influxdb2:
