version: "3.9"
services:
  db:
    image: postgres:14.0
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - "5438:5432"

  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - influxdb2:/.influxdb2
    ports:
      - "8086:8086"
  # Use the influx cli to set up an influxdb instance.

volumes:
  influxdb2:
